### ISSUE TITLE
Fail to start executable or start with CLI

### ISSUE THREAD

**Issue by Lg0enga** [theolivenbaum/electron-sharp#13]
Hi,

I switched from the Electron.NET package to work with .NET 7.

Only now at the `electron-sharp start` command I now get a JS error that I can't explain.

Can someone tell me why this is happening now? Where should `Helpers\bin` come from?

Here the output:
```
Found resource : ElectronSharp.CLI.ElectronHost.electron.manifest.json
Found resource : ElectronSharp.CLI.ElectronHost.package.json
Found resource : ElectronSharp.CLI.ElectronHost.ElectronHostHook.tsconfig.json
Found resource : ElectronSharp.CLI.ElectronHost.ElectronHostHook.package.json
Found resource : ElectronSharp.CLI.ElectronHost.main.js
Found resource : ElectronSharp.CLI.ElectronHost.build-helper.js
Found resource : ElectronSharp.CLI.ElectronHost.api.ipc.js
Found resource : ElectronSharp.CLI.ElectronHost.api.app.js
Found resource : ElectronSharp.CLI.ElectronHost.api.browserWindows.js
Found resource : ElectronSharp.CLI.ElectronHost.api.commandLine.js
Found resource : ElectronSharp.CLI.ElectronHost.api.dialog.js
Found resource : ElectronSharp.CLI.ElectronHost.api.dock.js
Found resource : ElectronSharp.CLI.ElectronHost.api.menu.js
Found resource : ElectronSharp.CLI.ElectronHost.api.notification.js
Found resource : ElectronSharp.CLI.ElectronHost.api.tray.js
Found resource : ElectronSharp.CLI.ElectronHost.api.globalShortcut.js
Found resource : ElectronSharp.CLI.ElectronHost.api.desktopCapturer.js
Found resource : ElectronSharp.CLI.ElectronHost.api.screen.js
Found resource : ElectronSharp.CLI.ElectronHost.api.shell.js
Found resource : ElectronSharp.CLI.ElectronHost.api.webContents.js
Found resource : ElectronSharp.CLI.ElectronHost.api.clipboard.js
Found resource : ElectronSharp.CLI.ElectronHost.api.autoUpdater.js
Found resource : ElectronSharp.CLI.ElectronHost.api.browserView.js
Found resource : ElectronSharp.CLI.ElectronHost.api.powerMonitor.js
Found resource : ElectronSharp.CLI.ElectronHost.api.nativeTheme.js
Found resource : ElectronSharp.CLI.ElectronHost.ElectronHostHook.index.ts
Found resource : ElectronSharp.CLI.ElectronHost.ElectronHostHook.connector.ts
Found resource : ElectronSharp.CLI.ElectronHost.ElectronHostHook..gitignore
Found resource : ElectronSharp.CLI.ElectronHost.splashscreen.index.html
node_modules in: C:\Users\len\source\repos\Goenga.Mettler.Sale\src\Goenga.Scale.Stock\obj\Host\node_modules
ElectronHostHook handling started...
Invoke electron.cmd - in dir: C:\Users\len\source\repos\Goenga.Mettler.Sale\src\Goenga.Scale.Stock\obj\Host\node_modules\.bin


---------------------------------------------------



electron.cmd "..\..\main.js"

App threw an error during load
Error: ENOENT: no such file or directory, access 'C:\Users\len\source\repos\Goenga.Mettler.Sale\src\Goenga.Scale.Stock\obj\Helpers\bin'
    at Object.accessSync (node:fs:259:3)
    at t.accessSync (node:electron/js2c/asar_bundle:2:8282)
    at Object.<anonymous> (C:\Users\len\source\repos\Goenga.Mettler.Sale\src\Goenga.Scale.Stock\obj\Host\main.js:51:15)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at loadApplicationPackage (C:\Users\len\source\repos\Goenga.Mettler.Sale\src\Goenga.Scale.Stock\obj\Host\node_modules\electron\dist\resources\default_app.asar\main.js:121:16)
    at Object.<anonymous> (C:\Users\len\source\repos\Goenga.Mettler.Sale\src\Goenga.Scale.Stock\obj\Host\node_modules\electron\dist\resources\default_app.asar\main.js:233:9)
```

**Comment by andrew-locklair** [comment]
I'm seeing this behavior as well. I believe `fs.accessSync` is returning `undefined` in https://github.com/theolivenbaum/electron-sharp/blob/ac26fd7a5bf6482c35284f4277766f5b18d49a36/ElectronSharp.Host/main.js#L49 even when there is a folder there. 

It appears that the original code intention should check for no exception thrown when calling `fs.accessSync` instead of looking for a truthy value. https://nodejs.org/api/fs.html#fsaccesssyncpath-mode
