### ISSUE TITLE
Auto updarer doesn't launch after migrating from Electron.NET

### ISSUE THREAD

**Issue by r-pankevicius** [theolivenbaum/electron-sharp#15]
### Our experience
The updater does not launch because it cannot deserialize the path to the install exe
Newtonsoft.Json.JsonReaderException
HResult=0x80131500
Message=Unexpected character encountered while parsing value: [. Path '', line 1, position 1.
Source=Newtonsoft.Json
StackTrace:
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
at Newtonsoft.Json.JsonTextReader.ReadAsString()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

This exception was originally thrown at this call stack:
Newtonsoft.Json.JsonTextReader.ReadStringValue(Newtonsoft.Json.ReadType)
Newtonsoft.Json.JsonTextReader.ReadAsString()
Newtonsoft.Json.JsonReader.ReadForType(Newtonsoft.Json.Serialization.JsonContract, bool)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, bool)

This issue happened when migrating from [Electron.NET](https://github.com/ElectronNET/Electron.NET) to here.

**Comment by r-pankevicius** [comment]
Will try to make a MR for this issue, for a moment adding most important part of it if I'll be late, as usual.

```csharp
﻿using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using static ElectronNET.API.BridgeConnector;

namespace ElectronNET.API.Entities.Serialization
{
    /// <summary>
    /// Converts releaseNotes attribute from (JSON older format coming from markdown) or from string to string.
    /// </summary>
    internal class ReleaseNotesConverter : JsonConverter
    {
        private static readonly CamelCaseNewtonsoftJsonSerializer Serializer = new();

        public override bool CanConvert(Type objectType)
        {
            throw new NotImplementedException("Not intended to write, just read.");
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null)
                return null;

            try
            {
                if (reader.TokenType == JsonToken.String)
                {
                    // New format: string is used for release notes (array of VersionReleaseNotes format must be used).
                    // Return as is.
                    return reader.Value?.ToString();
                }

                if (reader.TokenType == JsonToken.StartArray)
                {
                    reader.Read();

                    // Old format: array of objects is used for release notes. Convert to string.
                    List<VersionReleaseNotes> versionNotes = new();

                    while (reader.TokenType != JsonToken.EndArray)
                    {
                        versionNotes.Add(ReadVersionReleaseNote(reader));
                        reader.Read();
                    }

                    var jsonSerializeResult = Serializer.Serialize(versionNotes.ToArray());
                    return jsonSerializeResult.Json;
                }
            }
            catch (Exception ex)
            {
                throw new JsonSerializationException("Error converting release notes.", ex);
            }

            throw new FormatException($"Error converting release notes, unhandled toke type: {reader.TokenType}");
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException("Not intended to write, just read.");
        }

        private static VersionReleaseNotes ReadVersionReleaseNote(JsonReader reader)
        {
            reader.Read();
            
            var dictionary = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            while (reader.TokenType != JsonToken.EndObject)
            {
                if (reader.TokenType != JsonToken.PropertyName)
                    throw new FormatException($"Expected a property name, got {reader.TokenType}");
                string propertyName = reader.Value.ToString();
                reader.Read();
                if (reader.TokenType != JsonToken.String)
                    throw new FormatException($"Expected string, got {reader.TokenType}");
                string value = reader.Value.ToString();
                dictionary.Add(propertyName, value);
                reader.Read();
            }

            if (dictionary.Count != 2)
            {
                throw new FormatException($"Expected release version note object to have 2 keys, got {dictionary.Count}.");
            }

            if (!dictionary.ContainsKey("version") || !dictionary.ContainsKey("note"))
            {
                throw new FormatException($"Expected version and note keys, got: {string.Join(", ", dictionary.Keys)}");
            }

            var result = new VersionReleaseNotes
            {
                Version = dictionary["version"]
            };

            result.Notes.AddRange(
                dictionary["note"].Split("\n", StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries));

            return result;
        }
    }
}

```

**Comment by r-pankevicius** [comment]
ReleaseNotesConverter used here
```csharp
using ElectronNET.API.Entities.Serialization;
using System;

namespace ElectronNET.API.Entities
{
    /// <summary>
    /// 
    /// </summary>
    public class UpdateInfo
    {
        /// <summary>
        /// The version.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public UpdateFileInfo[] Files { get; set; } = Array.Empty<UpdateFileInfo>();

        /// <summary>
        /// The release name.
        /// </summary>
        public string ReleaseName { get; set; }

        /// <summary>
        /// The release notes.
        /// </summary>
        [Newtonsoft.Json.JsonConverter(typeof(ReleaseNotesConverter))]
        public string ReleaseNotes { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string ReleaseDate { get; set; }

        /// <summary>
        /// The staged rollout percentage, 0-100.
        /// </summary>
        public int StagingPercentage { get; set; }
    }
}
```

**Comment by r-pankevicius** [comment]
Closing, duplicate. Discussed and fixed: https://github.com/theolivenbaum/electron-sharp/discussions/10
